name: Java CI with Maven

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8.0.302+8'
        distribution: 'temurin'
        cache: maven

        
    - name: Execute Jar File
      env:
        RDS_URL: ${{ secrets.RDS_URL }}
        RDS_USERNAME: ${{ secrets.RDS_USERNAME }}
        RDS_PASSWORD: ${{ secrets.RDS_PASSWORD }}
        APP_PORT: ${{ secrets.APP_PORT }}
      run: |
        # Check if the port is in use and kill the process using it
        if lsof -t -i:$APP_PORT; then
          kill -9 $(lsof -t -i:$APP_PORT)
        fi
         mvn -B package --file pom.xml &
        # Execute the JAR file
        java -jar /home/ubuntu/actions-runner/_work/library/library/target/library-0.0.1-SNAPSHOT.jar
