name: Java CI with Maven

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 1.8
      uses: actions/setup-java@v3
      with:
        java-version: '1.8' # Changed to Java 1.8
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Execute Jar File
      run: sudo kill -9 `sudo lsof -t -i:${{secrets.APP_PORT}}` & sudo java -jar /home/ubuntu/actions-runner/_work/githubaction-springboot-env-ec2/githubaction-springboot-env-ec2/target/example-0.0.1-SNAPSHOT.jar & 

    # The optional step for uploading the dependency graph has been commented out
    # - name: Update dependency graph
    #  uses: advanced-security/maven-dependency-submission-action@v3
