name: Java CI with Maven

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8.0.302+8' # Specify a version of Java 8
        distribution: 'temurin' # AdoptOpenJDK has been rebranded to Eclipse Temurin
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Execute Jar File
      run: sudo kill -9 `sudo lsof -t -i:${{secrets.APP_PORT}}` & sudo java -jar /home/ubuntu/actions-runner/_work/library/library/target/library-0.0.1-SNAPSHOT.jar & 

    # If you want to enable the dependency graph update, uncomment the following lines
    # - name: Update dependency graph
    #  uses: advanced-security/maven-dependency-submission-action@v3
